FROM golang:1.25-alpine

WORKDIR /srv

COPY ./go.mod ./go.sum ./

RUN go mod download
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

COPY ./ ./

ENV PATH="/go/bin:${PATH}"

EXPOSE 80

CMD ["go", "run", "cmd/main.go"]
