# Stage 1: Build
FROM golang:1.25-alpine AS builder

WORKDIR /srv

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /srv/cmd
RUN go build -o /srv/main .

# Stage 2: Run
FROM alpine:latest
WORKDIR /srv

COPY --from=builder /srv/main .

ENV PATH="/go/bin:${PATH}"

EXPOSE 80
CMD ["./main"]
