x-go-tmpl: &go-tmpl
  image: vaross/private-projects:subscription-prod-latest
  restart: always
  platform: linux/amd64
  # volumes:
  #   - ./:/srv/:rw
  env_file:
    - .env
  networks:
    - subscription-network
  
services:
  subscription-nginx:
    container_name: subscription-nginx
    image: nginx:1.27-alpine
    platform: linux/amd64
    restart: always
    ports:
      - 81:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - subscription-network
    depends_on:
      - subscription-backend

  subscription-backend:
    <<: *go-tmpl
    container_name: subscription-backend

  subscription-postgres:
    container_name: subscription-postgres
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - subscription-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - subscription-network

volumes:
  subscription-postgres-data:
    driver: local

networks:
  subscription-network:
    name: subscription-network
    driver: bridge
