definitions:
  dto.Subscription:
    properties:
      end_date:
        example: 05-2026
        type: string
      id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
      price:
        example: 500
        type: integer
      service_name:
        example: Netflix
        type: string
      start_date:
        example: 02-2026
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
  http.CalculateTotalCostResponse:
    properties:
      from_date:
        example: 07-2025
        type: string
      service_name:
        example: Netflix
        type: string
      to_date:
        example: 12-2025
        type: string
      total:
        example: 500
        type: integer
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
  http.CreateSubRequest:
    properties:
      end_date:
        example: 12-2025
        type: string
      price:
        example: 400
        type: integer
      service_name:
        example: Yandex Plus
        type: string
      start_date:
        example: 07-2025
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
  http.CreateSubResponse:
    properties:
      id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
  http.ErrorResponse:
    properties:
      error:
        example: error
        type: string
    type: object
  http.UpdateSubRequest:
    properties:
      end_date:
        example: 12-2025
        type: string
      price:
        example: 500
        type: integer
      service_name:
        example: Netflix
        type: string
      start_date:
        example: 07-2025
        type: string
    type: object
info:
  contact: {}
paths:
  /subscriptions:
    get:
      consumes:
      - application/json
      description: List subscriptions with optional filters
      parameters:
      - description: User ID filter
        in: query
        name: user_id
        type: string
      - description: Service name filter
        in: query
        name: service_name
        type: string
      - description: Start date filter (MM-YYYY)
        in: query
        name: from_date
        type: string
      - description: End date filter (MM-YYYY)
        in: query
        name: to_date
        type: string
      - description: Limit number of results
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Subscription'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: List subscriptions
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Creates a subscription for a user
      parameters:
      - description: Subscription to create
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/http.CreateSubRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/http.CreateSubResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: Create a new subscription
      tags:
      - subscriptions
  /subscriptions/{id}:
    delete:
      consumes:
      - application/json
      description: Delete subscription by ID
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: Delete a subscription
      tags:
      - subscriptions
    get:
      consumes:
      - application/json
      description: Get a subscription by subscription ID
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Subscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: Get subscription by ID
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Update a subscription by ID
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      - description: Subscription update
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/http.UpdateSubRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: Update a subscription
      tags:
      - subscriptions
  /subscriptions/total-cost:
    get:
      consumes:
      - application/json
      description: Calculates the total cost of all subscriptions for a user and/or
        service within a given period. If from_date/to_date are not provided, defaults
        to the current month.
      parameters:
      - description: UUID of the user
        in: query
        name: user_id
        type: string
      - description: Filter by subscription service name
        in: query
        name: service_name
        type: string
      - description: Start of period, format MM-YYYY, defaults to start of current
          month
        in: query
        name: from_date
        type: string
      - description: End of period, format MM-YYYY, defaults to end of current month
        in: query
        name: to_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.CalculateTotalCostResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: Calculate total subscription cost
      tags:
      - subscriptions
swagger: "2.0"
